### ISSUE TITLE
Wrong issues returned by Github search API

### ISSUE THREAD

**Issue by Bernardstanislas** [onlydustxyz/marketplace#917]
Running:
```
curl --request GET \
  --url 'https://api.github.com/search/issues?q=repo%3Aod-mocks%2Fcool-repo-A%20is%3Apr%20is%3Amerged'
```

returns 1 issue instead of 2, as shown in https://github.com/od-mocks/cool-repo-A/pulls?q=is:pr+is:closed

Once the API is somehow fixed by Github, we should update our end to end test accordingly.

**Comment by ofux** [comment]
Not an issue anymore thanks to the github-indexer
